name: Docker Runner

on:
  push:
    branches: [ master ]

jobs:
  run:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Update ExenDLR
        run: |
          pip install -U pip
          pip install -U exendlr

      - name: Run Bot
        run: docker-compose up -d

      - name: Fetch Logs
        run: python3 -m exendlr clan-manager "bot is ready!"
